[package]
name = "rust-actix-postgres-multi-tenant"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
sqlx = { version = "0.8", features = ["runtime-tokio","postgres", "uuid", "chrono", "json"] }
actix-web = { version = "4.9", features = ["openssl"] }
tokio = { version = "1.40", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.10", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8.5"
aes-gcm = "0.11.0-pre.2"
hex = "0.4.3"
