application:
  protocol: https
  port: 8080
  host: 0.0.0.0
  certificate:
  cookie:
    secure: true  # Allow HTTP for local development
    content_security: "signed"  # Less strict for easier testing
    domain: null  # Use default domain
    name: "rust-actix-postgres-multi-tenant-cookie"
    path: "/"
    http_only: true
    same_site: "lax"  # Less strict, allows for easier cross-site testing
    session_ttl: 24

secrets:
  argon2_salt: ""
  argon2_key: ""
  aes256_gcm_key: ""
  hmac: ""

database:
  port: 5432
  host: "localhost"
  database_name: "rust-actix-postgres-multi-tenant"
  min_connections: 2
  max_connections: 4
  acquire_timeout: 750 #milliseconds
  max_lifetime: 900 #seconds
  idle_timeout: 150
  require_ssl: false

redis:
  host: "localhost"
  port: 6379
  database: 0
  tls: false
  pool_max_size: 16
  pool_timeout_in_seconds: 5
