name: Infra Manage DigitalOcean Resources

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment for which to create resources'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - development
          - production
      migration_user:
        description: 'The migration user to create'
        required: true
        default: 'migration_user'
      migration_password:
        description: 'The password for the migration user'
        required: true
        default: 'securepassword'
      region:
        description: 'Select the region for the database cluster'
        required: true
        default: 'fra1'
        type: choice
        options:
          - fra1  # Frankfurt
          - nyc1  # New York 1
          - nyc2  # New York 2
          - sfo1  # San Francisco 1
          - lon1  # London 1
      num_nodes:
        description: 'Select the number of nodes for the database cluster'
        required: true
        default: '1'
        type: choice
        options:
          - 1
          - 2
          - 3
          - 4
      size:
        description: 'Select the machine size for the database cluster'
        required: true
        default: 'db-s-1vcpu-1gb'
        type: choice
        options:
          - db-s-1vcpu-1gb  # Basic - $15/mo
          - db-s-1vcpu-2gb  # Basic - $25/mo
          - db-s-2vcpu-4gb  # Basic - $50/mo
          - db-s-4vcpu-8gb  # Professional - $120/mo
      engine:
        description: 'Select the database engine'
        required: true
        default: 'pg'
        type: choice
        options:
          - pg
          - mysql
          - redis
      version:
        description: 'Select the database version'
        required: true
        default: '16'
        type: choice
        options:
          - "15"
          - "16"

jobs:
  manage_resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up doctl
        uses: doctl/doctl-action@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Create Database Cluster
        id: create_cluster
        run: |
          ENVIRONMENT=${{ github.event.inputs.environment }}
          REGION=${{ github.event.inputs.region }}
          SIZE=${{ github.event.inputs.size }}
          NUM_NODES=${{ github.event.inputs.num_nodes }}
          ENGINE=${{ github.event.inputs.engine }}
          VERSION=${{ github.event.inputs.version }}
          ./infra/databases/infra_create_environment_database_cluster.sh "$ENVIRONMENT" "$REGION" "$SIZE" "$NUM_NODES" "$ENGINE" "$VERSION"

      - name: Create Dedicated Database
        id: create_database
        run: |
          ENVIRONMENT=${{ github.event.inputs.environment }}
          ./infra/databases/infra_create_environment_dedicated_database.sh "$ENVIRONMENT"

      - name: Create Migration User
        id: create_migration_user
        run: |
          ENVIRONMENT=${{ github.event.inputs.environment }}
          MIGRATION_USER=${{ github.event.inputs.migration_user }}
          MIGRATION_PASSWORD=${{ github.event.inputs.migration_password }}
          ./infra/databases/infra_create_environment_dedicated_database_migration_user.sh "$ENVIRONMENT" "$MIGRATION_USER" "$MIGRATION_PASSWORD"